# Generated by Django 3.0.11 on 2020-12-22 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, default='about', max_length=255, unique=True, verbose_name='Путь (ссылка)')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('email', models.CharField(max_length=55, verbose_name='E-mail')),
                ('location_text', models.CharField(max_length=128, verbose_name='Address')),
                ('location_google', models.TextField(max_length=512, verbose_name='Google iframe')),
                ('location_yandex', models.TextField(blank=True, max_length=512, null=True, verbose_name='Yandex location')),
                ('location_coord', models.CharField(blank=True, max_length=55, null=True, verbose_name='Geo coordinate')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(verbose_name='Position')),
                ('href', models.URLField(verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, unique=True, verbose_name='Name of social network')),
                ('uri', models.URLField(verbose_name='address')),
                ('show_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='Show Name')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FilePathField(verbose_name='File path')),
                ('slug', models.CharField(blank=True, default='about', max_length=255, unique=True, verbose_name='Slag for media')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hide', models.BooleanField(blank=True, default=False, verbose_name='Is hide')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='AboutTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_body', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('body', models.TextField(verbose_name='Full description')),
                ('lang_code', models.CharField(max_length=5, verbose_name='Language code')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caffemain.About')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
