# Generated by Django 3.0.11 on 2021-01-16 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201224_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='self_delivery',
            field=models.BooleanField(default=True, verbose_name='Self delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Днепр', max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+38(\\d{3})\\d{7}$')]),
        ),
    ]
